name: Build kata-static for amd64
on:
  workflow_dispatch: {}

jobs:
  build-asset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        asset:
          - stratovirt
          - cloud-hypervisor
          - virtiofsd
    
    steps:
      - uses: actions/checkout@v3

      - name: Build ${{ matrix.asset }}
        run: |
          make "${KATA_ASSET}-tarball"
          build_dir=$(readlink -f build)
          # store-artifact does not work with symlink
          sudo cp -r "${build_dir}" "kata-build"
        env:
          KATA_ASSET: ${{ matrix.asset }}
          TAR_OUTPUT: ${{ matrix.asset }}.tar.gz

      - name: store-artifact ${{ matrix.asset }}
        uses: actions/upload-artifact@v3
        with:
          name: kata-artifacts-amd64
          path: kata-build/kata-static-${{ matrix.asset }}.tar.xz
          retention-days: 2
          if-no-files-found: error

  create-kata-tarball:
    runs-on: ubuntu-latest
    needs: build-asset
    steps:
      - uses: actions/checkout@v3
      - name: get-artifacts
        uses: actions/download-artifact@v3
        with:
          name: kata-artifacts-amd64
          path: kata-artifacts
      - name: merge-artifacts
        run: |
          ./tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh kata-artifacts versions.yaml
      - name: store-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kata-static-tarball-amd64
          path: kata-static.tar.xz
          retention-days: 1
          if-no-files-found: error
